site_name: TUL

theme:
  name: material
  language: cs
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand          # sidebar otevřený podle sekce
    - navigation.footer          # tlačítka Next / Previous dole
    - toc.integrate
    - header.autohide
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.code.select        # umožní vybrat celý blok kódu jedním klikem
    - content.tabs.link
    - content.action.edit
    - content.action.view        # tlačítko „View source“ u každé stránky
    - content.footnote.tooltips  # poznámky pod čarou jako tooltipy
    - content.tooltips           # tooltipy na definice
    - announce.dismiss
  plugins:
    - search
    - glightbox        # klikneš na obrázek → otevře se v lightboxu
    - git-revision-date-localized
    - git-revision-date
    - minify:               # zmenší CSS/JS → rychlejší web
        minify_html: true
    - offline     
  palette:
    - scheme: default
      primary: blue
      accent: pink
      toggle:
        icon: material/weather-night
        name: Přepnout do tmavého režimu
    - scheme: slate
      primary: cyan
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Přepnout do světlého režimu
  font:
    text: "Inter"
    code: "Fira Code"

extra:
  analytics:
      provider: google
      property: G-XXXXXXXXXX
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/
    - icon: fontawesome/brands/discord
      link: https://discord.com/
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/
  logo: images/logo.png
  favicon: images/favicon.ico

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details        # skládací bloky (accordion)
  - pymdownx.mark           # zvýraznění textu ==takto==
  - pymdownx.keys           # vykreslování kláves jako <kbd>Ctrl</kbd>+<kbd>C</kbd>
  - pymdownx.progressbar    # progress bary [=60%]
  - pymdownx.tasklist       # checkboxy v seznamu
  - pymdownx.emoji
  - pymdownx.inlinehilite   # zvýraznění kódu v řádku `print("hi")`
  - pymdownx.snippets       # můžeš vkládat kousky MD z jiných souborů
  - pymdownx.highlight   # zvýraznění kódu s volbami
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
nav:
  - Home: index.md
  - Algoritmizace programovani Java 1: algoritmizace_programovani_java_1/index.md
  - Lineární algebra / Diskrétní mat: linearni_algerbra_diskretni_mat/index.md
  - Matematika 1: matematika_1/index.md
  - Shell Linux: shell_linux/index.md
  - Matlab: matlab/index.md
  - Inženýrství: inzenyrstvi/index.md
  - Dokumenty: dokumenty/index.md
